apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphwise-workflows.runners.fullname" . }}
  namespace: {{ include "graphwise-workflows.namespace" . }}
  labels:
    {{- include "graphwise-workflows.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
data:
  # See https://docs.n8n.io/hosting/configuration/environment-variables
  {{- if not (hasKey .Values.runners.configuration.environment "N8N_RUNNERS_LAUNCHER_HEALTH_CHECK_PORT") }}
  N8N_RUNNERS_LAUNCHER_HEALTH_CHECK_PORT: {{ .Values.runners.containerPorts.http | quote }}
  {{- end }}
  {{- /* Overrides from values.yaml */}}
  {{- if .Values.runners.configuration.environment -}}
    {{- range $key, $value := .Values.runners.configuration.environment -}}
      {{- if ne $value nil -}}
        {{- printf "%s: %s" $key (tpl ($value | toString) $ | quote) | nindent 2 -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
