apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graphwise-workflows.fullname" . }}
  namespace: {{ include "graphwise-workflows.namespace" . }}
  labels:
    {{- include "graphwise-workflows.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  strategy: {{ .Values.updateStrategy | toYaml | nindent 4 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "graphwise-workflows.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "graphwise-workflows.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ .Values.configuration.environment | toString | sha256sum }}
        checksum/configmap: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ include "graphwise-workflows.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- if .Values.schedulerName }}
      schedulerName: {{ .Values.schedulerName }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      volumes:
        {{- if .Values.persistence.existingVolumeClaim }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ tpl .Values.persistence.existingVolumeClaim $ }}
        {{- else if .Values.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "graphwise-workflows.fullname" . }}
        {{- else }}
        - name: storage
          emptyDir:
            {{- .Values.persistence.emptyDir | toYaml | nindent 12 }}
        {{- end }}
        {{- if .Values.tempVolume.enabled }}
        - name: temp-dir
          emptyDir:
            {{- .Values.tempVolume.emptyDir | toYaml | nindent 12 }}
        {{- end }}
        {{- if and .Values.runners.external .Values.runners.persistence.shared.enabled }}
        - name: shared-volume
          emptyDir:
            {{- .Values.runners.persistence.shared.emptyDir | toYaml | nindent 12 }}
        {{- end }}
      {{- with .Values.extraVolumes }}
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- if or .Values.affinity .Values.podAntiAffinity.enabled }}
      affinity:
        {{- if .Values.affinity  }}
          {{- tpl (toYaml .Values.affinity) $ | nindent 8 }}
        {{- end }}
        {{- if and .Values.podAntiAffinity.enabled (not .Values.affinity.podAntiAffinity) }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity.preset "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: {{ .Values.podAntiAffinity.topology }}
                labelSelector:
                  matchLabels:
                    {{- include "graphwise-workflows.selectorLabels" . | nindent 20 }}
          {{- else if eq .Values.podAntiAffinity.preset "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: {{ .Values.podAntiAffinity.topology }}
              labelSelector:
                matchLabels:
                  {{- include "graphwise-workflows.selectorLabels" . | nindent 18 }}
          {{- else }}
            {{- fail (printf "Unknown podAntiAffinity preset '%s'" .Values.podAntiAffinity.preset) }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints: {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.global.imagePullSecrets .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- include "graphwise-workflows.combinedImagePullSecrets" . | nindent 8 }}
      {{- end }}
      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "graphwise-workflows.name" . }}
          image: {{ include "graphwise-workflows.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPorts.http }}
            {{- with .Values.extraContainerPorts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "graphwise-workflows.fullname" . }}
          {{- with .Values.extraEnvFrom }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- if or
            .Values.configuration.encryption.existingSecret
            .Values.license.existingSecret
            .Values.configuration.postgresdb.credentials.existingSecret
            .Values.extraEnv
          }}
          env:
            {{- if .Values.configuration.encryption.existingSecret }}
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.configuration.encryption.existingSecret $ }}
                  key: {{ .Values.configuration.encryption.secretKey }}
            {{- else if or .Values.configuration.encryption.key .Values.configuration.encryption.autogenerate }}
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "graphwise-workflows.secrets.encryption.fullname" . }}
                  key: {{ .Values.configuration.encryption.secretKey }}
            {{- end }}
            {{- if .Values.license.existingSecret }}
            - name: N8N_LICENSE_ACTIVATION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.license.existingSecret $ }}
                  key: {{ .Values.license.licenseKey }}
                  optional: {{ .Values.license.optional }}
            {{- end }}
            {{- if and .Values.license.existingSecret .Values.license.tenantIdKey }}
            - name: N8N_LICENSE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.license.existingSecret $ }}
                  key: {{ .Values.license.tenantIdKey }}
                  optional: {{ .Values.license.optional }}
            {{- end }}
            {{- if .Values.configuration.postgresdb.credentials.existingSecret }}
            - name: DB_POSTGRESDB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.configuration.postgresdb.credentials.existingSecret $ }}
                  key: {{ .Values.configuration.postgresdb.credentials.usernameKey }}
            {{- end }}
            {{- if .Values.configuration.postgresdb.credentials.existingSecret }}
            - name: DB_POSTGRESDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.configuration.postgresdb.credentials.existingSecret $ }}
                  key: {{ .Values.configuration.postgresdb.credentials.passwordKey }}
            {{- end }}
            {{- if .Values.runners.external }}
              {{- if .Values.runners.configuration.token.existingSecret }}
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.runners.configuration.token.existingSecret . }}
                  key: {{ .Values.runners.configuration.token.tokenKey }}
              {{- else if or .Values.runners.configuration.token.token .Values.runners.configuration.token.autogenerate }}
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "graphwise-workflows.runners.secrets.token.fullname" . }}
                  key: {{ .Values.runners.configuration.token.tokenKey }}
              {{- end }}
            {{- end }}
            {{- with .Values.extraEnv }}
              {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: storage
              mountPath: {{ tpl .Values.persistence.path $ }}
            {{- if .Values.tempVolume.enabled }}
            - name: temp-dir
              mountPath: /tmp
            {{- end }}
            {{- if and .Values.runners.external .Values.runners.persistence.shared.enabled }}
            - name: shared-volume
              mountPath: {{ .Values.runners.persistence.shared.mountPath }}
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
              {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.runners.external }}
        - name: {{ include "graphwise-workflows.runners.name" . }}
          image: {{ include "graphwise-workflows.runners.image" . }}
          imagePullPolicy: {{ .Values.runners.image.pullPolicy }}
          {{- with .Values.runners.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.runners.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.runners.containerPorts.http }}
            {{- with .Values.runners.extraContainerPorts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "graphwise-workflows.runners.fullname" . }}
            {{- with .Values.runners.extraEnvFrom }}
              {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          env:
            {{- if .Values.runners.configuration.token.existingSecret }}
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ tpl .Values.runners.configuration.token.existingSecret . }}
                  key: {{ .Values.runners.configuration.token.tokenKey }}
            {{- else if or .Values.runners.configuration.token.token .Values.runners.configuration.token.autogenerate }}
            - name: N8N_RUNNERS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "graphwise-workflows.runners.secrets.token.fullname" . }}
                  key: {{ .Values.runners.configuration.token.tokenKey }}
            {{- end }}
            {{- with .Values.runners.extraEnv }}
              {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          volumeMounts:
          {{- if .Values.runners.persistence.shared.enabled }}
            - name: shared-volume
              mountPath: {{ .Values.runners.persistence.shared.mountPath }}
          {{- end }}
            {{- with .Values.runners.extraVolumeMounts }}
              {{- tpl (toYaml .) $ | nindent 12 }}
            {{- end }}
          {{- with .Values.runners.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.runners.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.runners.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.runners.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.runners.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- with .Values.extraContainers }}
          {{ tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
