{{- if and .Values.persistence.enabled ( not .Values.persistence.existingVolumeClaim ) }}
{{- $pvcAnnotatons := mergeOverwrite (deepCopy .Values.annotations) .Values.persistence.volumeClaim.annotations -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "graphrag-workflows.fullname" . }}
  labels:
    {{- include "graphrag-workflows.labels" . | nindent 4 }}
    {{- with .Values.persistence.volumeClaim.labels }}
      {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
  {{- with $pvcAnnotatons }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.persistence.volumeClaim.spec }}
    {{- tpl (toYaml .) $ | nindent 2 }}
  {{- end }}
{{- end }}
