{{- if and (not .Values.configuration.encryption.existingSecret) (or .Values.configuration.encryption.key .Values.configuration.encryption.autogenerate)  }}
  {{- $encryptionKey := "" -}}
  {{- if .Values.configuration.encryption.key -}}
    {{- $encryptionKey = .Values.configuration.encryption.key | b64enc }}
  {{- else if .Values.configuration.encryption.autogenerate }}
    {{- $encryptionSecret := (lookup "v1" "Secret" (include "graphwise-workflows.namespace" .) (include "graphwise-workflows.secrets.encryption.fullname" .) | default dict) -}}
    {{- $encryptionSecretData := (get $encryptionSecret "data" | default dict) -}}
    {{- $encryptionKey = coalesce (get $encryptionSecretData "N8N_ENCRYPTION_KEY") (randAlphaNum 24 | b64enc) }}
  {{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphwise-workflows.secrets.encryption.fullname" . }}
  namespace: {{ include "graphwise-workflows.namespace" . }}
  labels:
    {{- include "graphwise-workflows.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.configuration.encryption.secretKey }}: {{ $encryptionKey | quote }}
{{- end }}
