{{- if and .Values.runners.external (not .Values.runners.configuration.token.existingSecret) (or .Values.runners.configuration.token.token .Values.runners.configuration.token.autogenerate)  }}
  {{- $authToken := "" -}}
  {{- if .Values.runners.configuration.token.token -}}
    {{- $authToken = .Values.runners.configuration.token.token | b64enc }}
  {{- else if .Values.runners.configuration.token.autogenerate }}
    {{- $authTokenSecret := (lookup "v1" "Secret" (include "graphwise-workflows.namespace" .) (include "graphwise-workflows.secrets.encryption.fullname" .) | default dict) -}}
    {{- $authTokenSecretData := (get $authTokenSecret "data" | default dict) -}}
    {{- $authToken = coalesce (get $authTokenSecretData "N8N_RUNNERS_AUTH_TOKEN") (randAlphaNum 24 | b64enc) }}
  {{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphwise-workflows.runners.secrets.token.fullname" . }}
  namespace: {{ include "graphwise-workflows.namespace" . }}
  labels:
    {{- include "graphwise-workflows.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.runners.configuration.token.tokenKey }}: {{ $authToken | quote }}
{{- end }}
