{{- if .Values.serviceAccount.create -}}
{{- $saAnnotations := mergeOverwrite (deepCopy .Values.annotations) .Values.serviceAccount.annotations -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graphrag-workflows.serviceAccountName" . }}
  namespace: {{ include "graphrag-workflows.namespace" . }}
  labels:
    {{- include "graphrag-workflows.labels" . | nindent 4 }}
  {{- with $saAnnotations }}
  annotations:
    {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
{{- end }}
